"""Repository-owned scope check. Parse candidate data; never import its modules."""
import sys
import sysconfig

# The protected supervisor preloads sysconfig. Remove candidate search paths
# before importing any other module; a candidate cannot shadow the guard's stdlib.
_stdlib = sysconfig.get_path('stdlib')
sys.path = [_stdlib, _stdlib + '/lib-dynload']

import ast
import hashlib
import json
from pathlib import Path
import re
import tomllib


def check(root):
    root = Path(root)
    policy = json.loads((root / 'maintenance/scope.json').read_text())
    paths = sorted(p for p in root.rglob('*') if p.is_file() or p.is_symlink())
    errors = []
    if len(paths) > policy['max_files']:
        errors.append('repository file-count budget exceeded')
    if sum(p.stat().st_size for p in paths if not p.is_symlink()) > policy['max_bytes']:
        errors.append('repository byte budget exceeded')
    local = {p.stem for p in paths if p.suffix == '.py'} | set(policy['directories'])
    imports = set(sys.stdlib_module_names) | set(policy['external_imports']) | local
    for path in paths:
        name = path.relative_to(root).as_posix()
        parts = path.relative_to(root).parts
        lower = [p.lower() for p in parts]
        if path.is_symlink():
            errors.append(name + ': symlink'); continue
        if any(p in policy['denied_components'] for p in lower):
            errors.append(name + ': generated/vendor/framework directory')
        if len(parts) == 1:
            if name not in policy['root_files'] and not re.fullmatch(r'RELEASE_[0-9_]+\.md', name):
                errors.append(name + ': unapproved root file')
        elif parts[0] not in policy['directories']:
            errors.append(name + ': unapproved top-level directory')
        elif path.suffix.lower() not in policy['extensions']:
            errors.append(name + ': unapproved file type')
        if (path.name in {'package.json', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml'}
                or path.name.lower().startswith(('nuxt.config.', 'vue.config.'))):
            errors.append(name + ': unrelated frontend manifest')
        if (path.stat().st_size > policy['max_file_bytes'] and
                policy.get('known_large_files', {}).get(name) != hashlib.sha256(path.read_bytes()).hexdigest()):
            errors.append(name + ': file byte budget exceeded')
        if path.suffix == '.py':
            try:
                source = path.read_text()
                if any(marker in source[:512].lower() for marker in
                       ('automatically generated', 'generated by ', 'do not edit')):
                    errors.append(name + ': generated source')
                tree = ast.parse(source, filename=name)
                for node in ast.walk(tree):
                    names = ([n.name.split('.')[0] for n in node.names] if isinstance(node, ast.Import)
                             else [node.module.split('.')[0]] if isinstance(node, ast.ImportFrom)
                             and not node.level and node.module else [])
                    for module in names:
                        if module.lower() in policy['denied_frameworks'] or module not in imports:
                            errors.append(name + ': unapproved import ' + module)
            except (ValueError, UnicodeError, SyntaxError) as error:
                errors.append(name + ': invalid Python ' + type(error).__name__)
    try:
        project = tomllib.loads((root / 'pyproject.toml').read_text())
        dependencies = project.get('project', {}).get('dependencies', [])
        for group in project.get('dependency-groups', {}).values():
            dependencies += group
        for dependency in dependencies:
            name = re.split(r'[\[<>=!~; @]', dependency, maxsplit=1)[0].lower().replace('_', '-')
            if name not in policy['dependencies']:
                errors.append('pyproject.toml: unapproved dependency ' + name)
    except (ValueError, TypeError):
        errors.append('pyproject.toml: invalid dependency declaration')
    return {'passed': not errors, 'files': len(paths), 'findings': sorted(set(errors))[:50]}


if __name__ == '__main__':
    result = check(Path.cwd())
    print(json.dumps(result, ensure_ascii=False))
    raise SystemExit(0 if result['passed'] else 1)
